#!/usr/bin/env bun
/**
 * Generate skills registry from markdown files.
 * 
 * Reads skill markdown from:
 * - packages/opencode-hive/skills/[dir]/SKILL.md
 * 
 * Outputs: packages/opencode-hive/src/skills/registry.generated.ts
 */

import * as fs from 'fs';
import * as path from 'path';

interface SkillEntry {
  name: string;
  description: string;
  template: string;
}

function parseFrontmatter(content: string): { name: string; description: string; body: string } | null {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return null;

  const frontmatter = match[1];
  const body = match[2].trim();

  const nameMatch = frontmatter.match(/^name:\s*(.+)$/m);
  const descMatch = frontmatter.match(/^description:\s*(.+)$/m);

  if (!nameMatch || !descMatch) return null;

  return {
    name: nameMatch[1].trim(),
    description: descMatch[1].trim(),
    body,
  };
}

function discoverSkillFiles(rootDir: string): string[] {
  const files: string[] = [];

  // 1. opencode-hive/skills/**/SKILL.md
  const localSkillsDir = path.join(rootDir, 'packages/opencode-hive/skills');
  if (fs.existsSync(localSkillsDir)) {
    const entries = fs.readdirSync(localSkillsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        const skillPath = path.join(localSkillsDir, entry.name, 'SKILL.md');
        if (fs.existsSync(skillPath)) {
          files.push(skillPath);
        }
      }
    }
  }

  return files;
}

function main() {
  // Find the monorepo root (go up from scripts/ to opencode-hive/ to packages/ to root/)
  const scriptDir = path.dirname(new URL(import.meta.url).pathname);
  const rootDir = path.resolve(scriptDir, '../../..');

  console.log('[generate-skills] Root directory:', rootDir);

  const skillFiles = discoverSkillFiles(rootDir);
  console.log('[generate-skills] Found skill files:', skillFiles);

  const skills: SkillEntry[] = [];
  const seenNames = new Set<string>();

  for (const filePath of skillFiles) {
    const content = fs.readFileSync(filePath, 'utf-8');
    const parsed = parseFrontmatter(content);

    if (!parsed) {
      console.warn(`[generate-skills] Warning: Could not parse frontmatter in ${filePath}`);
      continue;
    }

    if (seenNames.has(parsed.name)) {
      throw new Error(`[generate-skills] Duplicate skill name "${parsed.name}" found in ${filePath}`);
    }

    seenNames.add(parsed.name);
    skills.push({
      name: parsed.name,
      description: parsed.description,
      template: parsed.body,
    });

    console.log(`[generate-skills] Parsed skill: ${parsed.name}`);
  }

  // Sort by name for consistent output
  skills.sort((a, b) => a.name.localeCompare(b.name));

  // Generate the registry file
  const outputPath = path.join(rootDir, 'packages/opencode-hive/src/skills/registry.generated.ts');

  const namesList = skills.map(s => JSON.stringify(s.name)).join(', ');

  const skillsArray = skills.map(s => {
    return `  {
    name: ${JSON.stringify(s.name)},
    description: ${JSON.stringify(s.description)},
    template: ${JSON.stringify(s.template)},
  }`;
  }).join(',\n');

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: scripts/generate-skills.ts
 * Run: bun run scripts/generate-skills.ts
 */

import type { SkillDefinition } from './types.js';

/**
 * List of builtin skill names.
 */
export const BUILTIN_SKILL_NAMES = [${namesList}] as const;

/**
 * All builtin skill definitions.
 */
export const BUILTIN_SKILLS: SkillDefinition[] = [
${skillsArray}
];
`;

  fs.writeFileSync(outputPath, output, 'utf-8');
  console.log(`[generate-skills] Generated: ${outputPath}`);
  console.log(`[generate-skills] Total skills: ${skills.length}`);
}

main();
